language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
  - node_modules


script:
  - npm run tslint
  - npm run build
  - npm run test
  - npm run test:int

after_success:
  - npm run coverage
