import { User as db } from "../connectors";
import { Authorize } from "./authorize";

export interface IUser {
  _id?: string;
  displayName?: string;
  email: string;
  password: string;
  autoGenerated?: boolean;
  firstName?: string;
  lastName?: string;
  isConsultant?: boolean;
  isCoach?: boolean;
  allowSharing?: boolean;
  birthday?: Date;
  startedPlaying?: Date;
  coaches?: Array<{ _id: string, name: string }>;
  friends?: Array<{ _id: string, name: string }>;
  token?: string;
}

export class User extends Authorize {

  /**
   * Finds User by id.
   * @param id User id.
   */
  public static findOneById(id: string) {
    return db.findOne({ _id: id });
  }

  /**
   * Finds User by token.
   * @param token authentication token.
   */
  public static findOneByToken(token: string) {
    return db.findOne({ token });
  }

  /**
   * Finds User by email.
   * @param token authentication token.
   */
  public static findOneByEmail(email: string) {
    return db.findOne({ email });
  }

  /**
   * Finds User by email.
   * @param token authentication token.
   */
  public static create(user: IUser): Promise<IUser> {
    return db.create(user);
  }

  /**
   * Updates previously restored user.
   * @param user User to be updated.
   */
  public static save(user: IUser): Promise<IUser> {
    return db.findByIdAndUpdate(user._id, user).then( (ret) => {
      return ret;
    });
  }
}
