import { User as db } from "../connectors";
import { Authorize } from "./authorize";
import { Document } from "mongoose";

export interface IUser extends Document {
  displayName: string;
  email: string;
  password: string;
  autoGenerated: boolean;
  firstName: string;
  lastName: string;
  isConsultant: boolean;
  isCoach: boolean;
  allowSharing: boolean;
  birthday: Date;
  startedPlaying: Date;
  coaches: Array<{ _id: string, name: string }>;
  friends: Array<{ _id: string, name: string }>;
  token: string;
}

export class User extends Authorize {

  /**
   * Finds User by id.
   * @param id User id.
   */
  public static findOneById(id: string) {
    return db.findOne({ _id: id });
  }

  /**
   * Finds User by token.
   * @param token authentication token.
   */
  public static findOneByToken(token: string) {
    return db.findOne({ token });
  }
}
