const user = `
  # User type representing players, coaches and consultants
  type User {
    _id: String,
    displayName: String,
    autoGenerated: Boolean,
    email: String,
    firstName: String,
    lastName: String,
    isConsultant: Boolean,
    isCoach: Boolean,
    allowSharing: Boolean,
    birthday: String,
    startedPlaying: String,
    coaches: [ User ],
    friends: [ User ],
    createdAt: String,
    updatedAt: String,
    measurements: [ Measurement ]
  }

  # Input type for creating new users
  input AutoUser {
    firstName: String!,
    lastName: String!,
    email: String!,
    birthday: String!,
    startedPlaying: String!,
    allowSharing: Boolean!
  }
`;

export default user;
